### ISSUE TITLE
Add utils for page and component layout

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-webview-ui-toolkit#116]
### Feature/component description

Investigate need for utils that aid extension authors when laying out pages and components. 

The main value prop of providing these utils is to avoid authors hardcoding one-off values for common scenarios like form stack spacing, grid layouts, and more.

**Comment by christian-bromann** [comment]
Just started to use this toolkit to build a configuration view and was looking for some sort of form components similar to https://bendera.github.io/vscode-webview-elements/components/vscode-form-container/ that matches the VSCode styleguide.
