### ISSUE TITLE
Indeterminate checkbox in light theme doesn't seem to be visible

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-webview-ui-toolkit#228]
Testing #133758

Looks like this:

![image](https://user-images.githubusercontent.com/19672699/135151232-002c5c1c-db01-4ea0-9af9-068023a76a32.png)

Same code in dark theme looks like this
![image](https://user-images.githubusercontent.com/19672699/135151279-51adc6af-8690-4960-bf07-a64fb14ad7df.png)

**Comment by hawkticehurst** [comment]
Thanks for the catch @rchiodo! It was a case of a specific design token existing in dark themes but not in light themes. Fixed now!
