### ISSUE TITLE
Mark the package as side-effect free

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-webview-ui-toolkit#253]
Adding `sideEffects: false` in the package.json [indicates](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) to bundlers (e.g. Webpack) that the package is side-effect free, which allows it to tree shake imports and reduce code size.

**Comment by hawkticehurst** [comment]
Ooh, yep that feels like a winner. Thank you (again) for the suggestions! 🙂

(This makes me quite happy too because I had always felt slightly icky leaving that script to live in the global scope and somewhat unattached from the rest of the toolkit.)
