### ISSUE TITLE
File select

### ISSUE THREAD

**Issue by worksofliam** [microsoft/vscode-webview-ui-toolkit#254]
### Feature/component description

A file select component: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

### Use case

We have a web view where a user can select an SSH key from their file system. We use the file selector, then pass the value back from the panel to the extension for the extension to read the file.

### Screenshots/references

Here is our existing UI:

![image](https://user-images.githubusercontent.com/3708366/136624504-f1d14b7a-ce02-4e3a-a5bb-666d16413cc0.png)

**Comment by yannickowow** [comment]
Hello,
I was also looking on this and going deeper on this subject. It looks like `HTMLInputElement` does not throw a `change` event containing the directory path if it is empty (currently out of W3C spec...). Do you think that is component will strictly extend a `input` element or it will be able to load an empty directory ?

Best Regards!

**Comment by chrisdholt** [comment]
> Hello, I was also looking on this and going deeper on this subject. It looks like `HTMLInputElement` does not throw a `change` event containing the directory path if it is empty (currently out of W3C spec...). Do you think that this component will strictly extend a `input` element or it will be able to load an empty directory (for example, through VS Code `Dialog`)?
> 
> Best Regards!

If the VSCode team decides to leverage the FAST component class and template it'll be form associated, but I believe the current plan for the change event is to map to the proxy element. You can take a look here at the progress: https://github.com/microsoft/fast/pull/5336/files

Could you elaborate on your need and possible implementation regarding your expectations above w/ loading an empty directory?

**Comment by yannickowow** [comment]
My current `webview` implementation uses a `input` with non-standard webkitdirectory attribute. It allows to select a folder instead of a file. However, it does not work if this one is empty.
I use this input component to select a folder to run a CLI in a given working directory.

But I guess that is out-of-spec, since W3C does not support directory selection yet

**Comment by chrisdholt** [comment]
> My current `webview` implementation uses a `input` with non-standard webkitdirectory attribute. It allows to select a folder instead of a file. However, it does not work if this one is empty. I use this input component to select a folder to run a CLI in a given working directory.
> 
> But I guess that is out-of-spec, since W3C does not support directory selection yet

Technically the FAST class can be extended to include non-standard attributes and behaviors such as this; it's a benefit of the approach we take. I don't think _we_ would include this attribute out of the gate as it's not standard, but it certainly could be included here if the VSCode team saw value in that specific non-standard attr. Alternatively, you could also extend yourself and depending on what the team decides to expose, you could recompose a custom file component with the vscode styles and your attr...all comes down to what gets built where :).

**Comment by worksofliam** [comment]
@daviddossett Hope you are having a good end of the year so far - jealous of your long time off!

My idea for work around:

1. I have a button and text
   * Button label: Chose file
   * Text label: ...
2. Click on the button -> `vscode.postMessage` which calls `scode.window.showOpenDialog`
3. When file is chosen, send back to frontend with `webview.postMessage`
4. Handle chosen file with `window.addEventListener` and update Text label with chosen path
   * Also update any internal variable

**Comment by daviddossett** [comment]
@worksofliam things have been on hold for a bit—we're just getting back up to speed on all things toolkit-related so I'll check back in soon.

**Comment by worksofliam** [comment]
@daviddossett Hey there. Just poking about this feature again.

**Comment by hawkticehurst** [comment]
Hey @worksofliam!

No updates on this yet, unfortunately. We've become really tightly resourced during the last year and now David and I have to split our time between the toolkit and a handful of other projects these days.

There is a chance I'll start to get some more time to work on toolkit stuff by the end of spring/early summer but it's still very TBD, so I'll try to circle back once I know more :)

**Comment by Quacken8** [comment]
> @daviddossett Hope you are having a good end of the year so far - jealous of your long time off!
> 
> My idea for work around:
> 
>     1. I have a button and text
>        
>        * Button label: Chose file
>        * Text label: ...
> 
>     2. Click on the button -> `vscode.postMessage` which calls `scode.window.showOpenDialog`
> 
>     3. When file is chosen, send back to frontend with `webview.postMessage`
> 
>     4. Handle chosen file with `window.addEventListener` and update Text label with chosen path
>        
>        * Also update any internal variables

Have you tried this? I cannot make the webview survive the opening of the dialog, even with `retainContextWhenHidden: true`

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
