### ISSUE TITLE
Add tree component

### ISSUE THREAD

**Issue by idoprz** [microsoft/vscode-webview-ui-toolkit#255]
Hi,

Please add tree component to the library.
I want to have a tree as part of my webview and not in a TreeView.
Use case can be a TreeView like panel with more controls like search control above the tree.

**Comment by daviddossett** [comment]
Thanks for raising this, @idoprz. We've received this request from other teams at Microsoft and usually recommend the native `TreeView` to avoid reinventing a fairly complex control. But I'm interested in learning more.

Could you tell me more about what sort of functionality you're looking for here?

cc @hawkticehurst

**Comment by atanasster** [comment]
Hi, 

I would love to see this added to the components, so it can be styled in accordance. 

My use-case is where a tree view is used inside of a grid to display property types: https://github.com/ccontrols/instant-documentation-vscode

 Currently using the `fast-tree-view`, and applying a few styles to make it look seamless inside of the `vscode-webvoiew-ui` components: 
 
 https://github.com/ccontrols/instant-documentation-vscode/blob/master/src/webview/fast-components.ts

**Comment by iddan** [comment]
Hey, I would love to see this added as well.
My use case is a tree view to show custom search results.
I created a poor-mans implementation just for demonstration purposes:

<img width="1024" alt="Screenshot 2021-12-12 at 1 43 47" src="https://user-images.githubusercontent.com/12671072/145695092-ea71832d-3d9b-4c43-885f-3d5f58851427.png">

**Comment by javahacks** [comment]
A tree component was great. However I would also consider a more complex tree-table control as shown in the first use case here https://github.com/microsoft/vscode-webview-ui-toolkit/issues/255#issuecomment-942414503 .

Here you see what I have in mind in [action](https://primefaces.org/primeng/showcase/#/treetable/size
). I believe there are many use cases where you have to show structured information in such a control (e.g. advanced debugger output).

**Comment by smorimoto** [comment]
Any updates on this? Right now we're embedding astexplorer as a webview, and to be honest, it looks weird when you see it in VSCode. I think it would also be useful to display the AST... 🙂

**Comment by seanpoulter-foci** [comment]
To propose another use case, we'd like to build a UI similar to a test runner that shows a file type icon on the left and a status pass/fail/progress/unknown on the right.

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
