### ISSUE TITLE
Missing dependency lodash-es

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode-webview-ui-toolkit#256]
### Describe the bug

Module not found: Error: Can't resolve `lodash-es` in `.../node_modules/@microsoft/fast-web-utilities/dist`

### To reproduce

1. Install the dependency to a VS Code extension with webpack bundling;
2. Start building your project
3. See it fail

### Expected behavior

The expected behavior would be that the `lodash-es` is defined as a dependency of the library, this way, it will not fail.

Also, the `FAST` docs recommend it: https://www.fast.design/docs/integrations/react#configuring-packages

### Screenshots

```bash
ERROR in ./node_modules/@microsoft/fast-web-utilities/dist/class-names.js
    Module not found: Error: Can't resolve 'lodash-es' in '.../node_modules/@microsoft/fast-web-utilities/dist'
     @ ./node_modules/@microsoft/fast-web-utilities/dist/class-names.js 1:0-49 7:14-24 9:18-26
     @ ./node_modules/@microsoft/fast-web-utilities/dist/index.js
     @ ./node_modules/@microsoft/fast-foundation/dist/esm/utilities/direction.js
     @ ./node_modules/@microsoft/fast-foundation/dist/esm/utilities/index.js
     @ ./node_modules/@microsoft/fast-foundation/dist/esm/index.js
     @ ./node_modules/@vscode/webview-ui-toolkit/dist/esm/checkbox/index.js
     @ ./src/panelWebView/index.tsx
```

### Desktop (please complete the following information):

-   OS Version: macOS
-   Toolkit Version: 0.8.1

**Comment by chrisdholt** [comment]
> @chrisdholt Do you know what version of FAST Element/Foundation @connor4312's changes will be published to?
> 
> If the changes are published to `fast-foundation` v2 I might still address this PR temporarily because it's going to take some time to convert the toolkit from v1 to v2.

Yes, those will unfortunately only be published into the current / latest packages.

**Comment by hawkticehurst** [comment]
Okay, thanks for the clarification! I'll go ahead add a quick PR to fix/resolve this issue now, but once we convert to foundation v2 (which is high on the priority list) I'll be able to remove lodash again 😅.
