### ISSUE TITLE
The scroll bar style in the Shadow DOM of the component is not unified with the outside

### ISSUE THREAD

**Issue by rulelee** [microsoft/vscode-webview-ui-toolkit#258]
![image](https://user-images.githubusercontent.com/11474005/136918958-84697904-e46b-4084-80dc-47f0b289832e.png)

**Comment by rulelee** [comment]
My project is based on Vue, and the temporary solution is shown in the figure
![Image](https://user-images.githubusercontent.com/11474005/137415955-4d539288-8edd-4790-b0a1-d70fae710401.png)

**Comment by daviddossett** [comment]
Cool to see this, @rulelee! Would you have any interest in raising a PR for this? That would be a massive help for us 🤞
