### ISSUE TITLE
Field label component

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode-webview-ui-toolkit#259]
### Feature/component description

Create a separate label component for your input fields: `<vscode-label>Label<vscode-label>`.

### Use case

Fields that haven't been supported yet by the toolkit, can then be developed ourselves and still use the same label styles without the need to duplicate the styles.

**Comment by daviddossett** [comment]
Great idea! We have this in the soon-to-be-released Figma toolkit. Agreed that it should be added here as well.

**Comment by hawkticehurst** [comment]
Hi @estruyf, 

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
