### ISSUE TITLE
Collapsible panel section component

### ISSUE THREAD

**Issue by estruyf** [microsoft/vscode-webview-ui-toolkit#260]
### Feature/component description

Creation of an accordion / collapsible section component. Similar to the panel sections which you have on the explorer panel.

### Use case

To create an experience that comes close to the OOTB VS Code experience in your webviews, it would be great to have a collapsible section component.

### Screenshots/references

![Screenshot 2021-10-12 at 10 38 41](https://user-images.githubusercontent.com/2900833/136922268-cc374cdc-7918-4564-a470-daefbb8d1123.png)

**Comment by estruyf** [comment]
@hawkticehurst I use the accordion to mimic the same behavior in my Front Matter panel (https://frontmatter.codes/) as all other panels from VS Code.

![image](https://user-images.githubusercontent.com/2900833/137079395-337d0552-c99a-469b-8049-7132264a6435.png)

I just want to be able to render any kind of HTML elements in it, not only a tree view.

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
