### ISSUE TITLE
Add toggle component

### ISSUE THREAD

**Issue by idoprz** [microsoft/vscode-webview-ui-toolkit#264]
### Feature/component description

We would like to have a toggle component.

### Use case

In some cases it makes more sense to use toggle and not checkbox, since the user expect immediate reaction.

**Comment by chrisdholt** [comment]
[Switch](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/switch/switch.spec.md#fast-switch) looks like it would be the relevant base here.

**Comment by daviddossett** [comment]
After some discussion we've decided to stick with only checkboxes for now to maintain alignment with VS Code core.
