### ISSUE TITLE
Feature Request: Add invalid CSS theming for `required` fields

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode-webview-ui-toolkit#270]
### Feature/component description

Implement VS Code error background/foreground/text color for required components

### Use case
If a field is not fulfilled with valid contents, components should be able to show to the user the invalid state.
_Please provide a use case to help us understand your request in context._

### Screenshots/references
Reference: https://developer.mozilla.org/fr/docs/Web/CSS/:invalid

Thanks :)

**Comment by crhenrici** [comment]
Is this still planned to be implemented?

**Comment by hawkticehurst** [comment]
Hi all,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
