### ISSUE TITLE
data-grid: styling of selected cell->code

### ISSUE THREAD

**Issue by atanasster** [microsoft/vscode-webview-ui-toolkit#278]
### Describe the bug

The `<code>` tag is not styled correctly when inside a selected cell

### To reproduce
The following code, select the second cell with the mouse:
```
<vscode-data-grid>
  <vscode-data-grid-row row-type="header">
    <vscode-data-grid-cell grid-column="1" cell-type="columnheader"> Name </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="2" cell-type="columnheader"> Type </vscode-data-grid-cell>
  </vscode-data-grid-row>
  <vscode-data-grid-row>
    <vscode-data-grid-cell grid-column="1">
      <a href="#">
        y*
      </a>
    </vscode-data-grid-cell>
    <vscode-data-grid-cell grid-column="2">
      <code>number</code>
    </vscode-data-grid-cell>
  </vscode-data-grid-row>
</vscode-data-grid>
```

### Expected behavior

Expected to have css styled applied to elements inside the cell

### Screenshots

![grab186](https://user-images.githubusercontent.com/6075606/138636637-f2fc0121-fc05-499c-a35d-f923a91fc370.jpg)

**Comment by hawkticehurst** [comment]
Quick update, I've been working on this + the data grid cell link issue and have run into some weird CSS specificity issues (i.e. my custom styling is not overriding the VS Code default styling for `<code>` and `<a>` tags) for yet to be determined reasons.

I'll be switching gears next week to work on the React sample extension/docs, but just wanted to chime in to say I haven't forgotten about this issue and will work on it as I have free moments.

**Comment by atanasster** [comment]
@hawkticehurst thanks for the update.
