### ISSUE TITLE
Text color of the dropdown is too light in light themes since v0.8.3

### ISSUE THREAD

**Issue by yy0931** [microsoft/vscode-webview-ui-toolkit#288]
### Describe the bug

The dropdown text is too light to see in the light+ (default light) theme

![image](https://user-images.githubusercontent.com/54441600/140065559-c42983af-9a0a-4d21-819b-8683b770fa09.png)

### To reproduce

Use vscode-webview-ui-toolkit-samples/all-components with the light+ theme

### Desktop (please complete the following information):

-   OS Version: Ubuntu 20.04
-   Toolkit Version: `v0.8.3`

**Comment by hawkticehurst** [comment]
Whoops! Thank you so much for the catch! 

Probably a design token snafu, adding to the backlog.
