### ISSUE TITLE
Events not consistently passed to wrapped React components

### ISSUE THREAD

**Issue by mattrothenberg** [microsoft/vscode-webview-ui-toolkit#289]
### Describe the bug

Howdy! I'm using [`@microsoft/fast-react-wrapper`](https://www.fast.design/docs/integrations/react) to convert these web-components into React components. I've noticed that, for some components, event handler props like `onInput` and `onClick` work totally fine, but for others, these props don't seem to do anything. For example, say I have the following wrapped React components 👇 

```tsx
import { provideReactWrapper } from '@microsoft/fast-react-wrapper';
import {
  vsCodeButton,
  vsCodeDropdown,
  vsCodeOption,
  vsCodeTextField,
} from '@vscode/webview-ui-toolkit';

const { wrap } = provideReactWrapper(React, provideFASTDesignSystem());

const VSCodeButton = wrap(vsCodeButton());
const VSCodeDropdown = wrap(vsCodeDropdown());
const VSCodeOption = wrap(vsCodeOption());
const VSCodeTextField = wrap(vsCodeTextField());
```

I'm able to use the `onClick` prop of the `VSCodeButton` component without trouble.
```tsx
<VSCodeButton
  onClick={() => {
    console.log('works! ✅');
  }}
>
  Click Me
</VSCodeButton>
```
Likewise, the `onInput` prop of the `VSCodeTextField` component works just fine.

```tsx
<VSCodeTextField
  onInput={(e) => {
    console.log('i see this logged ✅');
  }}
/>
```
However, the `onChange` prop of `VSCodeDropdown` _never_ seems to fire.
```tsx
<VSCodeDropdown
  onChange={(e) => {
    console.log('never works ❌');
  }}
>
  <VSCodeOption>Value #1</VSCodeOption>
  <VSCodeOption>Value #2</VSCodeOption>
  <VSCodeOption>Value #3</VSCodeOption>
</VSCodeDropdown>
```

Additionally, I've noticed that the prop types for the generated components aren't totally right. Here, `appearance` should be a valid prop, but TS throws an error.

<img width="275" alt="Screen Shot 2021-11-03 at 10 16 29 AM" src="https://user-images.githubusercontent.com/5148596/140077328-7e87bc6f-9ccd-4c7f-bd3e-b19d0f9565e2.png">

Note that this doesn't happen for the wrapped `fastButton` component.

```tsx
import { fastButton, provideFASTDesignSystem } from '@microsoft/fast-components';

const { wrap } = provideReactWrapper(React, provideFASTDesignSystem());

const FastButton = wrap(fastButton());
```

<img width="419" alt="Screen Shot 2021-11-03 at 10 17 54 AM" src="https://user-images.githubusercontent.com/5148596/140077603-3f5128ee-8ad1-4b7f-9ed8-60fc7c4f1b81.png">

### Expected behavior

I'd expect these props to work consistently across the generated React components, but it's quite likely that I'm misunderstand the respective APIs of these components.

Do you have any idea what might be going on?

### Desktop (please complete the following information):

-   Toolkit Version: `0.8.3`

**Comment by mattrothenberg** [comment]
@hawkticehurst Good question. I admittedly haven't run through every component, but the lack of prop behavior seems to be sporadic. Part of the problem is that I don't know which props to expect, so it could ultimately just be an education/documentation sort of issue.

I'll keep on digging and add stuff to this issue as I find it

**Comment by mattrothenberg** [comment]
For instance it turns out that I just might be using the dropdown component incorrectly 🤦 . The following code works.

```tsx
<VSCodeDropdown
  onInput={(e) => {
    console.log(e);
  }}
>
  <VSCodeOption>Value #1</VSCodeOption>
  <VSCodeOption>Value #2</VSCodeOption>
  <VSCodeOption>Value #3</VSCodeOption>
</VSCodeDropdown>
```

**Comment by hawkticehurst** [comment]
@mattrothenberg thought I'd give you a heads up that there is a conversation going on in another issue thread that might be very relevant/helpful to what we're talking about here.

https://github.com/microsoft/vscode-webview-ui-toolkit/issues/283#issuecomment-959734811

**Comment by hawkticehurst** [comment]
Also thanks for the updates! This is helpful information for me to keep in mind as I start to work on the React sample/docs.

**Comment by mattrothenberg** [comment]
@hawkticehurst Of course! I'm totally down to 🍐 on the React docs with you if you need an extra hand/brain :)

**Comment by hawkticehurst** [comment]
Ooh, I will happily take you up on that offer! Thank you!

I have some low-hanging issues/bugs that I'm trying to tackle this week, but I'll set up a time to chat sometime next week once I'm a bit more started up on the React work.

**Comment by xsteadybcgo** [comment]
> For instance it turns out that I just might be using the dropdown component incorrectly 🤦 . The following code works, though I still get a weird type error saying that `value` isn't a valid prop for the option component.
> 
> ```tsx
> <VSCodeDropdown
>   onInput={(e) => {
>     console.log(e);
>   }}
> >
>   <VSCodeOption>Value #1</VSCodeOption>
>   <VSCodeOption>Value #2</VSCodeOption>
>   <VSCodeOption>Value #3</VSCodeOption>
> </VSCodeDropdown>
> ```
> 
> <img alt="Screen Shot 2021-11-03 at 12 37 55 PM" width="527" src="https://user-images.githubusercontent.com/5148596/140103681-8d726f71-c622-4b0d-9a01-ee4a58e55717.png">

I also encountered this type error, I guess it's the type error of `fast-react-wrapper` package, maybe need to replace `ReactModule.HTMLAttributes` with `ReactModule.AllHTMLAttributes` , how should I define a type to solve it now?

**Comment by emilhammarstedtst** [comment]
onChange seems to be broken for radio-group as well.

Workaround that I use for now.
```
<div onClick={e => console.log(e.target.value); } >
    <VsCodeRadioGroup value={1} orientation="vertical">
        <VsCodeRadio value={1}>One</VsCodeRadio>
        <VsCodeRadio value={2}>Two</VsCodeRadio>
        <VsCodeRadio value={3}>Three</VsCodeRadio>
    </VsCodeRadioGroup>
</div>
```

**Comment by hawkticehurst** [comment]
This issue should be fixed now!

The problem was the result of a limitation in how TypeScript does type inference––you can read more about it in [this issue](https://github.com/microsoft/fast/issues/5387). The solution was to just be more explicit in adding the correct types when registering toolkit components.

Also as a heads up, I'm probably going to wait a bit to publish the changes so that the React component work also gets published at the same time.

**Comment by kevcao-certik** [comment]
@hawkticehurst It appears this type issue has appeared again:
```ts
          <VSCodeTextArea
            name="description"
            value={descContent}
            onInput={(e) => setDescContent(e.target?.value)}
            required
          />
```

<img width="534" alt="image" src="https://user-images.githubusercontent.com/83827747/210592626-556b209b-be56-41bb-a2af-2e651b74358f.png">

I'm currently using `@vscode/webview-ui-toolkit@1.2.1` and `typescript@4.9.4`.

**Comment by hawkticehurst** [comment]
Shoot well that's disappointing to hear. 😔 Thank you for the heads up, however! 

As a heads up, we're pretty tightly resourced at this time so it might take a bit of time for me to dive into this but I'll try and put this closer to the top of my priority list during the next few weeks.
