### ISSUE TITLE
Text Field password?

### ISSUE THREAD

**Issue by worksofliam** [microsoft/vscode-webview-ui-toolkit#306]
Hi

It doesn't seem text-field doesn't support passwords. E.g. typing where the characters are masked.

Here is my existing webview using a different UI framework.

![image](https://user-images.githubusercontent.com/3708366/146663978-964a0c92-27a9-4dc5-b705-0fefd9b4ed88.png)

**Comment by hawkticehurst** [comment]
Thanks for the call out @worksofliam!

This functionality is actually built-in, but it looks like I forgot to document it (apologies 😅). You can add the following attribute and it should solve your problem:

```html
<vscode-text-field type="password">Label</vscode-text-field>
```

**Comment by hawkticehurst** [comment]
I'll also add an item to the backlog to update our docs to reflect this.
