### ISSUE TITLE
VSCodeLink alignment incorrect when used inline

### ISSUE THREAD

**Issue by mattrothenberg** [microsoft/vscode-webview-ui-toolkit#324]
### Describe the bug

When using the `<VSCodeLink />` react component inside of a paragraph tag, the resulting alignment looks off.

![Screen Shot 2022-02-02 at 9 20 24 AM](https://user-images.githubusercontent.com/5148596/152171914-73be6e59-7cf5-4473-9e0a-ea040c3490ad.png)

### To reproduce
https://codesandbox.io/s/ecstatic-worker-ygz28?file=/src/App.tsx

```jsx
<p>
    This is an example of an{" "}
    <VSCodeLink href="https://github.com">Inline link</VSCodeLink> that
    should be aligned propertly
  </p>
```

### Expected behavior

I would expect the link text to be aligned with the surrounding paragraph text.

### Desktop (please complete the following information):

-   OS Version: Mac OS 11.6.2
-   Toolkit Version: `v0.9.0`

**Comment by hawkticehurst** [comment]
Thanks again for filing this!
