### ISSUE TITLE
Add react-specific documentation

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-webview-ui-toolkit#331]
### Feature/component description

With the recent release of React toolkit components, there are a couple of edge cases and gotchas that need to be documented for those who will be using the toolkit React components. Namely, there needs to be an inclusion of:

- Using enums for a handful of component attributes at this time (#325 / [fast issue](https://github.com/microsoft/fast/issues/5494))
- The need to use `onInput` instead of `onChange` events for keystroke events ([fast issue](https://github.com/microsoft/fast/issues/5551))
- General addition of React code samples in markdown files
- Other stuff? (cc @mattrothenberg / @daviddossett)

**Comment by mattrothenberg** [comment]
These look good to me.

I'd still like to get that Storybook (https://github.com/microsoft/vscode-webview-ui-toolkit/pull/312) published, as we can provide code samples there. Unfortunately I just _cannot_ get around that weird error we're seeing around certain props not being applied.
