### ISSUE TITLE
vscode-dropdown JS generated option with selected property not selected

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode-webview-ui-toolkit#332]
### Describe the bug

When generating vscode-option elements inside a vscode-dropdown and setting `.selected = true;` on one, it should be selected in the UI, but isn't (reset by an internal reset if no values are selected check)

### To reproduce

```html
<vscode-dropdown id="testdropdown"></vscode-dropdown>
<script>
	var dropdown = document.getElementById("testdropdown");
	for (var i = 1; i <= 3; i++)
	{
		var option = document.createElement("vscode-option");
		option.value = "v" + i;
		option.textContent = "Value " + i; // Value 1, Value 2, Value 3
		dropdown.appendChild(option);
		if (i == 2)
		{
			option.selected = true;
			// to fix bug uncomment this:
			// option.setAttribute("selected", "selected");
		}
	}
	// expected "Value 2" to be selected now
</script>
```

### Expected behavior

Value 2 should be selected in the example, not Value 1

### Desktop (please complete the following information):

-   OS Version: VSCode 1.64.0 on Electron 13.6.8 on ArchLinux i3 (X11)
-   Toolkit Version: `v0.9.0`

### Additional context

There is an internal check ran asynchronously, which resets the value if no option is selected. However it checks if the option is selected by checking if the _attribute_ selected is set. (not the property)

The `selected` property of vscode-option should probably modify the DOM attribute.

It seems to be reset here:

![toolkit.js line 8715](https://wfr.moe/f6rYkL.png)

https://github.com/microsoft/fast/blob/eff36b2834b7709cc2281738007019fd264c3d31/packages/web-components/fast-foundation/src/listbox/listbox.ts#L537

alternatively it would be possible to also check the property instead of making the property modify the attribute, which is what combobox does:

https://github.com/microsoft/fast/blob/256fe07122c2838e6bf0edd639a539b9ceeaa1bf/packages/web-components/fast-foundation/src/combobox/combobox.ts#L546

**Comment by WebFreak001** [comment]
(made an issue in FAST: https://github.com/microsoft/fast/issues/5583)

**Comment by hawkticehurst** [comment]
Thanks for the issue and for filing an issue with FAST as well! I'll keep an eye on the progress and merge any changes the FAST team adds once they are available!

**Comment by CharlieGreenman** [comment]
any work being done on this one?

**Comment by hawkticehurst** [comment]
Unfortunately, no work on our end since this is an upstream issue within FAST

I've been checking the issue that @WebFreak001 filed with FAST every month or so for the last year but still haven't seen any movement on it

**Comment by CharlieGreenman** [comment]
That's pretty funny. I found a workaround via overriding component so it worked out in the end. Thank you again

**Comment by hawkticehurst** [comment]
Oh nice! Glad you were able to get yourself unblocked in that case 😁

**Comment by jdneo** [comment]
Hi @CharlieGreenman, how did you solve it? Would you mind sharing about it?

**Comment by hawkticehurst** [comment]
Hi all,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
