### ISSUE TITLE
Webview Enhancements 

### ISSUE THREAD

**Issue by rangav** [microsoft/vscode-webview-ui-toolkit#335]
### Extension/feature description
In Notepad example
https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/notepad

1.  How can we show alert when user is trying to close webview without saving? like in default editor
2. Italic title option for readonly mode like in editor
3. Dirty Indicator (black dot beside title) for unsaved mode like in default editor 

### Use case

I am creator of [Thunder Client](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client) extension, I am unable to do all the above listed features in my extension

if you can enable above features for webview then we can better design extensions that work like default editor

**Comment by daviddossett** [comment]
Hey @rangav, this looks like something the [Custom Editor API](https://code.visualstudio.com/api/extension-guides/custom-editors) would be best suited for.

As far as the toolkit it concerned, any issues or requests related to the that API would be better filed on the main [VS Code repo](https://github.com/microsoft/vscode/issues).

**Comment by rangav** [comment]
Hi @daviddossett do you have example project how to use customEditor api with virtual documents?.

 I have have any physical documents or files

**Comment by rangav** [comment]
Can you provide Notes example project with custom editor api similar to below one

https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/default/notepad

**Comment by daviddossett** [comment]
[Here's the "official" Custom Editor sample](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample) in case you hadn't see it yet.

We'll take a look at the toolkit samples to see if it makes sense to use that. Could very well be a good idea given that the Notepad sample also suffers from lack of proper document states.

**Comment by rangav** [comment]
That sample is based on physical files, which I don't have in my extension 

I am looking for virtual document, like the notes app

if you can add another notes example using customEditor API that will be very useful

**Comment by rangav** [comment]
I created a new feature request to provide notes example with CustomEditor api https://github.com/microsoft/vscode-webview-ui-toolkit/issues/337
