### ISSUE TITLE
Fix minor style issues across the toolkit

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-webview-ui-toolkit#342]
### Describe the bug

Tracking an issue for myself to do the following:
- Ensure font stack mirrors VS Code on all platforms
- Double check dimensions on all components
- Double check interaction states on all components

**Comment by hawkticehurst** [comment]
Had another thought: might be nice to also do some light compare and contrast between our component styles and the CSS defined in the `vscode/src/vs/base/browser/ui` component folders.

**Comment by daviddossett** [comment]
Yep great idea!
