### ISSUE TITLE
React - blank page when using ui-toolkit react component

### ISSUE THREAD

**Issue by eouin** [microsoft/vscode-webview-ui-toolkit#355]
### React component resulting on error

When using a react component in a react webview It result with an error on the console

here is the sample code:

![CleanShot 2022-03-21 at 17 10 12](https://user-images.githubusercontent.com/526128/159327219-ff97d7b0-ceda-479c-96c0-039bd7236816.jpg)

when running the extension via the Run and Debug tab, it result on an error:
![CleanShot 2022-03-21 at 17 12 45](https://user-images.githubusercontent.com/526128/159327510-ac0f4452-eb9c-4a73-93dd-e71e8ea7e1e2.jpg)

![CleanShot 2022-03-21 at 17 19 16](https://user-images.githubusercontent.com/526128/159328630-726ef6d9-6da9-4086-ad09-02ccb816cff0.jpg)

Here is the version used:

![CleanShot 2022-03-21 at 17 15 09](https://user-images.githubusercontent.com/526128/159327932-b8b58632-4696-4d4b-95f0-7d4a9fa640fa.jpg)

-   OS Version: MacOS latest
-   Toolkit Version: 0.9.2

**Comment by daviddossett** [comment]
Phew! Glad to hear that you worked it out.

**Comment by hawkticehurst** [comment]
^ +1 to that!
