### ISSUE TITLE
Please add a combo box component

### ISSUE THREAD

**Issue by rbergman** [microsoft/vscode-webview-ui-toolkit#370]
### Feature request

A combobox component with autocomplete support would be extremely valuable for easily building richer user experiences with this library.

### Expected behavior

Exactly as it works in the FAST component library.

### Current behavior

No combo box is available.

### Use case

Many form fields require a combination of either predefined static choices or free-form user input.  Offering the existing FAST combobox solution would be perfect.

### Screenshots/references

![CleanShot 2022-04-14 at 08 20 15](https://user-images.githubusercontent.com/273778/163410320-63e9b038-923e-4921-bb8c-be4b1c461dcf.png)

**Comment by hawkticehurst** [comment]
Thanks for the request @rbergman! 

We actually had a prototype combobox component implemented many months ago, but cut it right before our public preview because we were running into some gnarly accessibility issues. 

It's been on our backlog to fix those issues and reintroduce the combobox since that time, so we can definitely try to revisit this component sooner than later now that we recently shipped v1.0 and are scoping out what we should tackle next.

**Comment by rbergman** [comment]
That would be most appreciated, it's a pretty key component for our needs.  BTW, thanks for creating this library, it's really terrific to be able to build user interfaces that match the overall IDE.  Looking forward to more components as they become available 😄

**Comment by hawkticehurst** [comment]
Good to know! Hopefully reintroducing it to the toolkit should go more smoothly/quickly this time.

Also, you're welcome, and thank you! Thrilled to hear it's doing its job well––definitely looking forward to expanding the toolkit to help out extension devs even more 😊

**Comment by svew** [comment]
I definitely could use this as well, I've had to hack together my own version of it for now

**Comment by sklinov** [comment]
Adding a huge +1 to this feature request - that would be extremely valuable.

**Comment by MaxKless** [comment]
It's a bit hacky but for anyone looking for a functioning combo box implementation using `@microsoft/fast-foundation`, have a look here: https://github.com/nrwl/nx-console/pull/1807

I reused `<vscode-option>` and pretty much just copied the select box styles from the toolkit otherwise.

**Comment by hawkticehurst** [comment]
Hi all,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
