### ISSUE TITLE
bug: vscode-inputbox min and max attributes aren't respected

### ISSUE THREAD

**Issue by SethFalco** [microsoft/vscode-webview-ui-toolkit#373]
### Describe the bug

Similar to Chromium, when the type is set to `number`, it only allows numerical characters. (i.e. `\d\.e` and whatever else, and it also adds an up/down arrow and lets user increment/decrement the number with their mouse.

However, the `min` and `max` attributes aren't being applied, usually a user can still type smaller numbers than the `min`, but using the buttons or scroll wheel should not. In this case, regardless of method, the user can always set the number below the minimum.

### To reproduce

```html
<vscode-inputbox id="since-input" type="number" value="-1" min="-1"></vscode-inputbox>
```

### Expected behavior

Users should not be able to use the UI elements (up/down arrow) or scroll wheel to set the number outside the min or max value.

### Current behavior

Users can set the number in an input box to a number outside the confinements with the scroll wheel or buttons.

### Desktop (please complete the following information):

Version: 1.68.0-insider
Commit: 624bbc4fb966bfa34e9486e320a64a138ac337fd
Date: 2022-05-12T05:21:29.328Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.10.0-14-amd64 snap

### Additional context

I originally filed this in microsoft/vscode, what was redirected here:
* https://github.com/microsoft/vscode/issues/149561

**Comment by hawkticehurst** [comment]
Thanks for the bug report @SethFalco!

I'm currently on vacation until the end of May, so I won't be able to dive into this deeply for a few weeks.

From a casual reading, however, I wanted to clarify what UI component your using exactly? 

We don't ship a `vscode-inputbox` (only a `vscode-text-field` and `vscode-text-area`). Are you using one of those or something different?

cc @daviddossett

**Comment by SethFalco** [comment]
Huh… that might be my bad then. 🤔 
`vscode-inputbox` is indeed the one used in the project.

Looks like I'm an idiot. 🤦🏾 
Sorry about that, I just assumed it was part of the Visual Studio Code API.

Seems it comes from [bendera/vscode-webview-elements](https://github.com/bendera/vscode-webview-elements).

Sorry for the noise, I'll close this ticket and report/PR the fix there.
