### ISSUE TITLE
Add size attribute like the text-field

### ISSUE THREAD

**Issue by idoprz** [microsoft/vscode-webview-ui-toolkit#375]
Hi,

text-field has a size attribute, which is great. When I create a form, I control the size of the text field, but the drop down seems small in comparison. Can you add size attribute for the drop down as well?

**Comment by idoprz** [comment]
Hi,
You are right, I since there is a size attribute in the text field, I didn't really relized I can do this via CSS 😂. That's my bad.
I guess it still makes sense to have this attribute to have similar capabilities.

Thanks for your response!

**Comment by hawkticehurst** [comment]
Haha no worries at all 😂

But agreed, this is probably a "yes and" situation where CSS should ideally solve the problem but I think it still makes sense to add the size attribute for consistency across the components.

**Comment by daviddossett** [comment]
Did a bit of digging here and realized that the notion of `size` when it comes to HTML `select` elements is related to the number of options visible when opened, not the width of the parent component:

From [MDN's docs on `size`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attr-size):
> If the control is presented as a scrolling list box (e.g. when multiple is specified), this attribute represents the number of rows in the list that should be visible at one time. 

That's also reflected in the FAST component's (which this is built on) [API spec](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/select/select.spec.md#api).

> `size` - Indicates the height of the listbox based on the amount

**Comment by hawkticehurst** [comment]
Thanks for digging into this @daviddossett! 

In that case, I want to prioritize staying aligned with the HTML spec in our components, so we won't implement a `size` attribute in the way that you described @idoprz and let CSS be the method for adjusting the width of a dropdown.
