### ISSUE TITLE
TextField looses focus in Notebook view

### ISSUE THREAD

**Issue by bigbug** [microsoft/vscode-webview-ui-toolkit#377]
### Describe the bug
The TextField looses focus in Notebook view (tested with react).

### To reproduce

Render a text field and also a dropdown in a notebook renderer.
While mouse down, the text field receives the focus. However on mouse up the text field looses the focus. Therefore the user is unable to enter anything into the text field.
Once the dropdown field is removed from the code base, this only happens once after opening a notebook view. So it seems that adding the DropDown leads to the text field constantly loosing focus. Whereas it happens only once if it used without the dropdown.

```typescript
export const activate: ActivationFunction = context => {
  return {
    renderOutputItem(outputItem, element) {
      const root = createRoot(element);
      root.render(
        <>
          <VSCodeTextField />
          <VSCodeDropdown>
            <VSCodeOption>a</VSCodeOption>
            <VSCodeOption>b</VSCodeOption>
          </VSCodeDropdown>
        </>,
      );
    },
    disposeOutputItem(outputId) {
      // Do any teardown here. outputId is the cell output being deleted, or
      // undefined if we're clearing all outputs.
    }
  };
};
```

### Expected behavior

The text field does not loose focus. Even on the first click/focus.

### Current behavior

The text field looses the focus.

### Screenshots

<img width="672" alt="Screenshot 2022-06-18 at 18 08 32" src="https://user-images.githubusercontent.com/27259/174447111-17518d6c-f7e5-4726-a8c3-6c6fc401bab4.png">

### Desktop (please complete the following information):

- OS Version: macOS 12.3.1
- VSCode: 1.68.1
- Toolkit Version: v1.0.0

### Additional context

The issue could not be reproduced with VSCode 1.67 and before. So the problem seems to have been introduced with VSC 1.68.

Sample Code:
[Archive.zip](https://github.com/microsoft/vscode-webview-ui-toolkit/files/8933944/Archive.zip)

**Comment by bigbug** [comment]
Probably could be related to this issue: [https://github.com/microsoft/vscode/issues/151981](https://github.com/microsoft/vscode/issues/151981)

**Comment by daviddossett** [comment]
cc @rebornix

**Comment by daviddossett** [comment]
Got it, thanks. I'll keep this open until that has been fixed 👍

**Comment by bigbug** [comment]
@hawkticehurst : I can confirm the bug also occurs with
```typescript
root.render(
        <>
          <VSCodeDropdown>
            <VSCodeOption>a</VSCodeOption>
            <VSCodeOption>b</VSCodeOption>
          </VSCodeDropdown>
          <VSCodeTextField></VSCodeTextField>
        </>,
      );
```

**Comment by hawkticehurst** [comment]
@bigbug yeah I figured that would probably be the case. Thank you for double-checking regardless!

With that being the case, I'll default to what @daviddossett said -- we'll keep this issue open until the other one is fixed

**Comment by hawkticehurst** [comment]
@bigbug looks like an [upstream PR](https://github.com/microsoft/vscode/pull/154999) was merged yesterday which should fix this problem!

It will be shipped in the next VS Code recovery build (i.e. patch release).

**Comment by hawkticehurst** [comment]
@bigbug I believe these changes should have shipped now! If you don't mind, could you verify that the fix works so we can close this issue?

**Comment by bigbug** [comment]
@hawkticehurst I can confirm that it works again. Thanks for your help!

**Comment by hawkticehurst** [comment]
Fantastic! Thrilled to hear it :)
