### ISSUE TITLE
Support `autoFocus` attribute in React-wrapped components

### ISSUE THREAD

**Issue by evangrayk** [microsoft/vscode-webview-ui-toolkit#381]
### Feature request

When using react component bindings, the `autofocus`/`autoFocus` prop does not work on `<VSCodeTextArea>` and `<VSCodeTextField>`.

### Expected behavior

React components `<VSCodeTextArea>` and `<VSCodeTextField>` should accept an `autoFocus` prop which causes the components to focus when mounted.

### Current behavior

[Note: React polyfills the autoFocus attribute on normal input elements](https://github.com/facebook/react/issues/11851#issuecomment-351672131) so that they can be consistent and work with mounting component beyond just the first page load. It appears this polyfill does not happen when using with `VSCodeTextArea` and `VSCodeTextField`. 

You can provide `autofocus` without a typescript warning, and it will add `autofocus` to the innermost `<textarea>` of the `<vscode-text-area>`. However, this doesn't have the intended effect: the text area is not focused when added to the DOM (because the HTML attribute only applies on first page load in most browsers).

It's possible to work around this issue by re-implementing this behavior using react hooks, however it's quite annoying to do so. (This is a separate issue but `ref`s are difficult to use with this library because of the types of components—you have to do an ugly type cast to make it work)

### Use case

It's very common to auto-focus text areas and text fields in forms that you want people to fill out. This is a common react idiom, so not having this makes the textarea/textfield components feel like weird bespoke components instead of acting like textareas and textfields that we're used to using.

### Screenshots/references

To test this in an isolated environment, I added a `<VSCodeTextArea autofocus>Text Area!</VSCodeTextArea>` to the [vscode-webview-ui-toolkit sample create-react-app project](https://github.com/microsoft/vscode-webview-ui-toolkit-samples/tree/main/frameworks/hello-world-react-cra).

When you launch the webview, it does not auto-focus the text area.

**Comment by daviddossett** [comment]
Thanks for filing, @evangrayk. We'll take a look at this and will report back 👍

**Comment by felipetodev** [comment]
any way to do a inputRef.current.focus()

when component is mounted?

<VSCodeTextField ref={inputRef} />

ref and itemRef doesn't seem to work

**Comment by drriguz** [comment]
I'd like to make the textarea increase height automatically. However, the ref is hard to use:
```
const textareaRef = useRef<HTMLInputElement>(null);
<VSCodeTextArea ref={textareaRef} ...
```
and there's an error:

```
Type 'RefObject<HTMLInputElement>' is not assignable to type 'LegacyRef<Component<PropsWithChildren<Partial<Pick<TextArea, "normalize" | "form" | "slot" | "template" | "title" | "animate" | "className" | "required" | "hidden" | "dir" | "blur" | "click" | "focus" | ... 296 more ... | "handleTextInput">> & ReactEvents<...> & HTMLAttributes<...> & { ...; }>, {}, any>> | undefined'.
  Type 'RefObject<HTMLInputElement>' is not assignable to type 'RefObject<Component<PropsWithChildren<Partial<Pick<TextArea, "normalize" | "form" | "slot" | "template" | "title" | "animate" | "className" | "required" | "hidden" | "dir" | "blur" | "click" | "focus" | ... 296 more ... | "handleTextInput">> & ReactEvents<...> & HTMLAttributes<...> & { ...; }>, {}, any>>'.
```

But I don't know how to cast it ..

**Comment by hawkticehurst** [comment]
Hi all,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
