### ISSUE TITLE
Uncentered text/icons when `vscode-button` has a width greater than 300px

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-webview-ui-toolkit#384]
### Describe the bug

The `button` element within the shadow DOM of a `vscode-button` currently has a max-width of 300px defined. 

This means that when a `vscode-button` has a width of 100% inside a parent container with a width greater than 300px it results in un-centered text/icons.

### To reproduce

Add a `vscode-button` to a `div`.

Set the `vscode-button` width to 100% and set the `div` width to 500px.

### Expected behavior

VS Code buttons should have center-aligned text/icons no matter their width.

### Current behavior

VS Code buttons will only have centered text/icons up to 300px in width.

### Screenshots

With max-width of 300px:

<img width="460" alt="vscode-button-max-width" src="https://user-images.githubusercontent.com/39639992/181844264-d5a2221d-4413-4982-acd4-5293dbadb958.png">

Without max-width:

<img width="460" alt="vscode-button-max-width-removed" src="https://user-images.githubusercontent.com/39639992/181844315-0b4dd3ae-62a3-4566-ad83-458082c0e4ae.png">

### Desktop (please complete the following information):

-   Toolkit Version: `v1.0.0`

**Comment by hawkticehurst** [comment]
The solution is to literally just remove this line of code: https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/button/button.styles.ts#L88

**Comment by hawkticehurst** [comment]
cc @daviddossett

**Comment by chaiwattsw** [comment]
@hawkticehurst Can I take this issue?

**Comment by hawkticehurst** [comment]
@chaiwattsw absolutely! Go for it 🙂

**Comment by chaiwattsw** [comment]
> @chaiwattsw absolutely! Go for it 🙂

Thanks!
