### ISSUE TITLE
Docs for React  vscode-webview-ui-toolkit

### ISSUE THREAD

**Issue by ilan-pinto** [microsoft/vscode-webview-ui-toolkit#387]
### Feature request

The docs for React version are very limited. 
I am missing the following 
- how to debug 
- how to use the different components

**Comment by daviddossett** [comment]
Any specific ideas or requests for those two items?

**Comment by hawkticehurst** [comment]
Hey @ilan-pinto! 

Echoing what David said earlier could you be a bit more specific in what types of debugging/component usage scenarios you're hoping to see from our docs? Was there something you were specifically struggling with that could help inform how we write any new docs?

**Comment by hawkticehurst** [comment]
Hi @ilan-pinto, 

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
