### ISSUE TITLE
Link: Support for 'word-break'

### ISSUE THREAD

**Issue by charisk** [microsoft/vscode-webview-ui-toolkit#388]
(Apologies if this is possible already and I have missed some docs on how)

### Feature request

It would be great if `vscode-link` would obey the `word-break` property e.g. `word-break: break-word`. In our case we have a `vscode-link` inside a `div` that has `word-break` but long lines aren't broken.

### Expected behavior

The lines to break.

### Current behavior

The text is overflowing its content box.

### Use case

We have some file path links that can get quite long and would like them to not overflow the table/grid they're in.

### Screenshots/references

<img width="864" alt="image" src="https://user-images.githubusercontent.com/311693/183026786-09d75e0e-00a0-448e-a155-73ec64121201.png">

**Comment by charisk** [comment]
Thank you for fixing this @daviddossett! Do you know when the fix will be released?

**Comment by hawkticehurst** [comment]
@charisk sorry, that's on me 😅

I got back from vacation last week and was hoping to complete some other work so I could publish everything in one batch, but alas other to-do list items got in the way of that.

Regardless, I'll just go ahead and publish the current changes by the end of today so you're not blocked anymore!

**Comment by hawkticehurst** [comment]
Alright just published a [patch release](https://github.com/microsoft/vscode-webview-ui-toolkit/releases/tag/v1.0.1)! Let me know if this resolves your issue.

**Comment by charisk** [comment]
Awesome, thank you so much for the fix and the ship!

**Comment by hawkticehurst** [comment]
You're welcome! Thanks for opening the issue in the first place!
