### ISSUE TITLE
Add split button component

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode-webview-ui-toolkit#39]
### Problem
There is currently no [FAST Foundation](https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation) split button base component that can be used to implement a VSCode split button.

### Solution
A custom implementation of a split button could be pursued, however, there is active work by the FAST team to create a [split button spec](https://github.com/microsoft/fast/pull/4083) that will eventually be implemented and added to FAST Foundation.

To maintain consistent usage of FAST Foundation across this library the progress of this base component will be monitored and when the base component is available the VSCode split button will be implemented and added to this library.

**Comment by chrisdholt** [comment]
@hawkticehurst We'd love to dig in here with you. Open UI is starting to look here, it would be great to dig in on your thoughts and requirements and re-ignite the split button conversation.

**Comment by hawkticehurst** [comment]
@chrisdholt Yes, please! I (and I'm also sure @daviddossett) would love to dig into that with you all!
