### ISSUE TITLE
RadioGroup focus TypeError: Cannot read properties of undefined (reading 'setAttribute')

### ISSUE THREAD

**Issue by christian-bromann** [microsoft/vscode-webview-ui-toolkit#390]
### Describe the bug

We are using the UI toolkit in our [demo extension](https://marketplace.visualstudio.com/items?itemName=stateful.awesome-ux) and experience an issue when using a RadioGroup. The HTML looks as follows:

![Screenshot 2022-08-18 at 18 00 29](https://user-images.githubusercontent.com/731337/185441149-74bb5242-ac84-4922-b3aa-aec4aec4ec09.png)

Clicking around causes the following error:

```
toolkit.js:10990 Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at RadioGroup$1.focusOutHandler (toolkit.js:10990:29)
    at BindingBehavior.slotted.property [as binding] (toolkit.js:10896:277)
    at BindingBehavior.handleEvent (toolkit.js:1320:25)
RadioGroup$1.focusOutHandler @ toolkit.js:10990
slotted.property @ toolkit.js:10896
handleEvent @ toolkit.js:1320
```

It seems to be connected to the underlying web components framework: https://github.com/microsoft/fast/blob/b32eb1004960da95b74dba7f111ee859b6655896/packages/web-components/fast-foundation/src/radio-group/radio-group.ts#L292-L293

### To reproduce

Download the extension and click around in the radio group.

### Expected behavior

No error.

### Current behavior

See error above.

### Desktop (please complete the following information):

-   OS Version: [e.g. `macOS 11.3.1`]
-   Toolkit Version: [e.g. `v0.8.0`]

**Comment by hawkticehurst** [comment]
Hey @christian-bromann!

I think this is actually "technically correct" behavior. The `vscode-radio-group` component is only designed to accept `vscode-radio` components but not `vscode-checkbox`'s.

The implementation of `vscode-radio-group` follows the [HTML spec for the `radiogroup` role](https://developer.mozilla.org/en-US/docs/web/accessibility/aria/roles/radiogroup_role) where:

> A radiogroup is a type of select list that can only have a single entry, or radio, checked at any one time.

So having checkboxes that can all be selected inside a radiogroup breaks the specification.

I believe (???) the semantically correct way to wrap/contain checkboxes is to put them inside `fieldset` and `legend` elements, however, [using forms inside VS Code webviews is something that is somewhat limited](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/366#issuecomment-1091140096) from my understanding. I have an open issue in the toolkit to [more deeply explore form usage in webview/toolkit context](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/371) but just haven't had time to get around to it yet.

In the meantime, if you're just trying to wrap/contain the `vscode-checkbox` components, I've used `section`/`div` tags in the past, which works fine.

Hope this helps and let me know if you have any more questions! Happy to chat about this more.

**Comment by hawkticehurst** [comment]
I'm going to go ahead and close this issue based on what I said above.

I did, however, create a [new issue](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/392) that will update the docs to better clarify this reality.

Also, @christian-bromann, feel free to add any questions/comments on this thread and I'll keep an eye out.
