### ISSUE TITLE
Web View Does Not Publish

### ISSUE THREAD

**Issue by necatiarslan** [microsoft/vscode-webview-ui-toolkit#391]
Hi,
I developed an extension using web view UI toolkit components.
Components are working in debugging and I am not getting any compilation or runtime error.
However when I create a vsix package and install it, any of the component does not work.

Any idea on this ?

repo:https://github.com/necatiarslan/airflow-vscode-extension/blob/main/src/dagView.ts 

this is after vsix
![Screen Shot 2022-08-19 at 01 35 27](https://user-images.githubusercontent.com/1336688/185550262-58dd330a-e5e5-480d-87fa-98fea87c594e.png)

this is debug
![Screen Shot 2022-08-19 at 01 37 36](https://user-images.githubusercontent.com/1336688/185550468-d3abfa67-c686-45aa-b904-04d6c781a8a1.png)

**Comment by r3m0t** [comment]
Did you try the command `Developer: Toggle Developer Tools` and check the Console?

**Comment by necatiarslan** [comment]
Here is a screenshot.

![Screen Shot 2022-08-19 at 07 45 01](https://user-images.githubusercontent.com/1336688/185611587-5b0b8370-ea62-49cc-b194-1bfdc30bdee8.png)

**Comment by necatiarslan** [comment]
Here is the screenshot

![Screen Shot 2022-08-19 at 08 15 30](https://user-images.githubusercontent.com/1336688/185616458-d2100f35-c589-48a7-90b4-6e2f346f4de5.png)

**Comment by r3m0t** [comment]
That `dist/toolkit.js` path should be in your vsix, but it isn't. Unzip it to check. Also check `.vscodeignore` and make sure the correct argument is being passed to `asWebviewUri`.

**Comment by necatiarslan** [comment]
I fixed the issue by removing node_modules/** line in the vscodeignore file.

**Comment by hawkticehurst** [comment]
Oh nice! Was finally just about to follow up on this issue, but happy to see this all got sorted. 

@r3m0t thank you so much for providing some help/guidance 😊

**Comment by necatiarslan** [comment]
Thanks, guys for your help. I am working on the first airflow extension project which you can trigger dags (data pipelines), see logs and much more.

**Comment by hawkticehurst** [comment]
Ooh, that's awesome! Best of luck with it!

If you run into any other issues with the toolkit feel free to open another issue and we'll be happy to help.

Also on the off chance you haven't seen these resources if you have more general, non-toolkit, extension development questions there's a really helpful [VS Code GitHub Discussions](https://github.com/microsoft/vscode-discussions/discussions) board and a wonderful [VS Code Dev Community Slack](https://aka.ms/vscode-dev-community) where devs are regularly asking and answering each other's questions.
