### ISSUE TITLE
Components Needed

### ISSUE THREAD

**Issue by necatiarslan** [microsoft/vscode-webview-ui-toolkit#393]
Hi,
Thanks for creating these wonderful vs code extension components.
I am working on my first extension project now and I need these components.
I hope this post with help you to decide which components will be added in the next releases.

- DateTime Picker
- Charts (Bar, Line, Pie)
- Masked Text Field
- 

My Extension Repo : https://github.com/necatiarslan/airflow-vscode-extension

**Comment by hawkticehurst** [comment]
Hi @necatiarslan,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
