### ISSUE TITLE
Popover support

### ISSUE THREAD

**Issue by kevin-s-wang** [microsoft/vscode-webview-ui-toolkit#407]
### Feature request

Popover support

### Expected behavior

Here's the control that exists in vscode:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/24372742/191183051-c66fca0a-7b07-48b4-990c-3300033606e8.png">

### Current behavior
No such support

### Use case

Display tips etc.

**Comment by hawkticehurst** [comment]
Thanks for the feature request @kevin-s-wang!

Could you share a bit more info about how you would hope to use this component? 

Would this popover only be usable in a list like shown in the screenshot above or would the popover be usable in other places? What else besides display tips would you hope to use this for? 

Basically, any more details that can help us get an idea of what you hope to use this component for and where/how it would be used would be greatly appreciated

Thanks 😊

**Comment by daviddossett** [comment]
FWIW these are called markdown hovers in VS Code core. Consumers can render custom content in a generic hover. Interesting to think about bringing those in here if there were enough use cases.

**Comment by kevin-s-wang** [comment]
@hawkticehurst  @daviddossett  Thank you for your replies. We want to use it for telling users more information about an item like an icon, a list item when the mouse is hovering. We can implement our own popover component in a webview, but if it's implemented in the toolkit that'd be more convenient for us.

**Comment by hawkticehurst** [comment]
Hi @kevin-s-wang,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
