### ISSUE TITLE
Data grid: long headers not aligned with cells

### ISSUE THREAD

**Issue by fengtan** [microsoft/vscode-webview-ui-toolkit#411]
### Describe the bug

If a [data grid](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/README.md) has long headers, then those aren't always aligned with cells.

### To reproduce

Create a data grid by following the [official documentation](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/README.md#basic-data-grid) and specify many long headers with no space.

For instance:

```js
  const row1 = {};
  const row2 = {};
  for(i=1;i<20;i++) {
    row1["aVeryLongHeader"+i] = "value"+i;
    row2["aVeryLongHeader"+i] = "aVeryLongValue"+i;
  };
  document.getElementById("grid").rowsData = [row1, row2];
```

### Expected behavior

Headers and cells should be aligned so you can clearly identify the columns:

![proposed](https://user-images.githubusercontent.com/1483301/198926294-8441c9f1-2d68-4607-8537-98e2e07cd61b.png)

### Current behavior

Headers are not aligned with the cells. Note that all cells are aligned so the problem is specific to headers vs regular cells:

![current](https://user-images.githubusercontent.com/1483301/198926320-638bf273-02f0-450a-ac32-530608c8f32b.png)

### Desktop (please complete the following information):

-   OS Version: `Ubuntu 20.04.5 LTS`
-   Toolkit Version: `v1.0.1`

**Comment by hawkticehurst** [comment]
Thank you for this catch and subsequent PR! Tested it all on my end and was able to validate both the issue and the fix :)
