### ISSUE TITLE
Add small button variant

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-webview-ui-toolkit#413]
Given their usage both in VS Code core and in various extensions, I think it would be useful to provide a small variant of the text button. This would also extend to any future split button as shown in an example below:

## GitHub Pull Requests Extension

<img width="967" alt="CleanShot 2022-11-01 at 11 21 05@2x" src="https://user-images.githubusercontent.com/25163139/199309199-8f867ec6-83df-4eb4-90b0-5eefd9ad5f11.png">

<img width="925" alt="CleanShot 2022-11-01 at 11 21 14@2x" src="https://user-images.githubusercontent.com/25163139/199309204-354851cb-0b70-4a9f-8d72-cc84806ea66b.png">

## Core

<img width="648" alt="CleanShot 2022-11-01 at 11 22 44@2x" src="https://user-images.githubusercontent.com/25163139/199309161-0dc9f275-e3cb-4fc1-83cd-35c0248d19be.png">

<img width="294" alt="CleanShot 2022-11-01 at 11 25 10@2x" src="https://user-images.githubusercontent.com/25163139/199309624-b4f5d126-e18d-4e2d-8dab-f48d49df18c4.png">

**Comment by hawkticehurst** [comment]
Yeah, I'm on board with this 👍
