### ISSUE TITLE
Webpack 5 failed to resolve... the package.json contains '"type": "module"

### ISSUE THREAD

**Issue by jonasboardwalker** [microsoft/vscode-webview-ui-toolkit#423]
### Describe the bug

I'm using Webpack 5.72.0 for my React WebView-based extension for VSCode. When I'm trying to export any component from "@vscode/webview-ui-toolkit/react" I get two errors:

<img width="781" alt="Screenshot 2022-12-03 at 19 24 00" src="https://user-images.githubusercontent.com/20488748/205456205-c69790cc-f20a-4045-9261-1309c0134817.png">

### To reproduce

1. Import any component from @vscode/webview-ui-toolkit/react
2. Use it in your webview-based application with webpack 5

### Expected behavior

Should compile with no errors

### Current behavior

Compiles with errors

### Desktop:

-   OS Version: [e.g. `macOS Ventura 13.0 (22A380)`]
-   Toolkit Version: [e.g. `v1.2.0"`]

### Additional context

Webpack 5 is not new and used in many applications. It would be useful to migrate this project to the 5th version.

**Comment by jonasboardwalker** [comment]
I found the solution here [here](https://github.com/webpack/webpack/issues/11467#issuecomment-691873586).

Basically, just add this rule to the module.rules of your webpack config:
`{
  test: /\.m?js/,
  resolve: {
    fullySpecified: false
  }
}`

**Comment by hawkticehurst** [comment]
@jonasboardwalker happy to see you were able to find a solution! (Thank you for sharing it in this thread too!)
