### ISSUE TITLE
vscode-optgroup component

### ISSUE THREAD

**Issue by scholarsmate** [microsoft/vscode-webview-ui-toolkit#440]
### Feature request

VS Code component for the standard HTML `optgroup` element for organizing `vscode-dropdown` `vscode-options`.

### Expected behavior

To be able to organize `vscode-options` in a `vscode-dropdown` using `vscode-optgroup` in the same way standard HTML `options` can be organized in a `select` using `optgroup`.

### Current behavior

There currently is no work-alike to `optgroup` in the library that I'm aware of.

### Use case

Selecting one of various kinds of encodings in a hex editor.

### Screenshots/references

Here, I'm using a standard `select`, `options` and `optgroup` for the encodings, but would prefer to use `vscode-dropdown` with `vscode-options` and `vscode-optgroup` for the same look-and-feel:

<img width="464" alt="Screen Shot 2023-01-03 at 5 06 22 PM" src="https://user-images.githubusercontent.com/2205472/210449829-3d0bb0fa-f655-478e-8e47-04483609f9d8.png">

<img width="473" alt="Screen Shot 2023-01-03 at 5 06 33 PM" src="https://user-images.githubusercontent.com/2205472/210449843-d155d3f7-8811-413f-a917-61cc441cf178.png">

**Comment by hawkticehurst** [comment]
Hi @scholarsmate,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
