### ISSUE TITLE
Typings/Paths for react/index.d.ts are not correctly generated 

### ISSUE THREAD

**Issue by erkenberg** [microsoft/vscode-webview-ui-toolkit#455]
### Describe the bug

`npm run build` generates a `react/index.d.ts` which uses incorrect paths in the current version (1.2.1):

E.g. (occurs multiple times in the file):
```ts
export declare const VSCodeBadge: [...] <import("../dist/dist/index.js") ...
```

### To reproduce

1. Clone the repository
2. run `npm install && npm run build`
3. check the generated `react/index.d.ts`

### Expected behavior

`dist` only appears once on the path, as it was the case before this commit https://github.com/microsoft/vscode-webview-ui-toolkit/commit/acadb09779c9f1934b8e920278a908217b11241f: 

```ts
export declare const VSCodeBadge: [...] <import("../dist/index.js") ...
```
### Current behavior

Starting with the linked commit and later, `dist` appears twice in the path, which is incorrect, as the path `../dist/dist/...` does not exist.

### Desktop (please complete the following information):

-   OS Version: `macOS 13.2.1`
-   Toolkit Version: `v1.2.1`

**Comment by hawkticehurst** [comment]
Thanks for the catch @erkenberg! Just merged a PR that should fix the issue and will publish a patch release shortly

**Comment by erkenberg** [comment]
Awesome, thanks for the quick fix @hawkticehurst !
