### ISSUE TITLE
vscode-data-grid support row selections

### ISSUE THREAD

**Issue by ppyaxin** [microsoft/vscode-webview-ui-toolkit#465]
fast-data-grid has just supported row selections, how soon could it applys to this toolkit?

https://github.com/microsoft/fast/pull/5786

**Comment by hawkticehurst** [comment]
Hey @ppyaxin! 

We [have plans](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/448#issuecomment-1411251709) to adopt the next major versions of FAST by the end of June '23, so I think you can safely expect row selection support by then.

I'll keep this issue open to make sure I confirm row selection is included when we adopt those changes. Beyond that let me know if you have any other questions :)

**Comment by hawkticehurst** [comment]
Hi @ppyaxin,

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
