### ISSUE TITLE
Have a VSCode Extension wait on the disposal of a webview panel? 

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode-webview-ui-toolkit#487]
I have a VSCode Extension that makes extensive use of a TreeView. 
I am replacing some usage of VSCode QuickInput with web views as I have some user input that extends to a number of fields and QuickInput is painful when having to request multiple sets of user input.

The "problem" I am facing is how to have the Extension wait till the Webview panel is disposed. 
For example , One panel, might require some credentials and until they are provided, the Treeview should not be accessible. 
This is easy using QuickInput as it provides the ability to await.

I haven't found any means of handling waiting for the dispose of the panel  to complete.  It may simply not be possible.  
However, I would have expected  other webapp users may also want their code to wait on the completion of the panel being disposed.

If you have a Webview with a number of text fields  etc that need to be passed to the extension then the extension must have the ability to wait to receive those fields . It seems a fundamental requirement.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by daviddossett** [comment]
@davidkjackson54 this seems to be related to the overall VS Code extension API. I'd suggest moving this topic to the [VS Code Community Discussion](https://github.com/microsoft/vscode-discussions/discussions) as a starting point.

**Comment by davidkjackson54** [comment]
VSCode Webview provides the means to trap the Webview on.dispose of the panel. If there was a means to wait on that, it would probably help.
