### ISSUE TITLE
Support description panel for the dropdown options

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-webview-ui-toolkit#524]
### Feature request

Support adding description for the dropdown options. Like the setting in VS Code
![image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/6193897/f8d60fca-eebf-43d0-8e5f-11ab6269f3bd)

**Comment by hawkticehurst** [comment]
Hi @jdneo, 

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
