### ISSUE TITLE
Feature Request: sash 

### ISSUE THREAD

**Issue by mitsuruog** [microsoft/vscode-webview-ui-toolkit#534]
### Feature request

It would be great if this toolkit provided a sash based on [the VS Code sash](https://github.com/microsoft/vscode/blob/2d50c20ad2b1739274384e60bb05dca2b15af064/src/vs/base/browser/ui/sash/sash.ts).

### Expected behavior

As the user clicks and moves the boundary of the sash, the area of the divided screen changes.
It is good to be able to pass an initial percentage of the initial split as an initial value.

For reference.

https://split.js.org/

### Current behavior

The toolkit doesn't provide the component. 
we need to implement it and it would be hard to adjust the theme that is provided by vscode.

### Use case

This is used when users want to split the screen in WebView。

### Screenshots/references

<img width="906" alt="スクリーンショット 2023-12-07 10 34 55" src="https://github.com/microsoft/vscode-webview-ui-toolkit/assets/1703219/88ba4630-5c4e-4a9e-b4c4-e2c622199ee6">

**Comment by hawkticehurst** [comment]
Hi @mitsuruog,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
