### ISSUE TITLE
Checkboxes squish when their parent container's width shrinks

### ISSUE THREAD

**Issue by benvillalobos** [microsoft/vscode-webview-ui-toolkit#539]
### Describe the bug

We have an extension in VSCode called "Visual Studio Code for Education". In our VSCode extension's webview, when a checkbox's div shrinks in width, the width of the checkbox also shrinks in width.

### To reproduce

1. https://vscodeedu.com (account is free, just need a msft account)
2. https://vscodeedu.com/courses/intro-to-python -> Start Course
3. On the left hand side Table of Contents, navigate to
	4. Unit 3 - If
	5. Lesson 4 - If Statement Patterns
	6. "And vs Nested If"
	7. Scroll down
	8. Verify by expanding the right file over the left

### Expected behavior

Checkboxes should retain their dimension

### Current behavior

Checkboxes width's shrink as their containing div's width shrinks.

### Screenshots
Notice how the checkboxes on the left squish as I reduce the width of our webview. ![checkboxes](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/4691428/b837d32f-0cee-487f-b20f-53a3ef547679)

### Desktop (please complete the following information):

-   OS Version: Windows 11 22621.3007
-   Toolkit Version: 1.4.0

### Additional context

The element containing these checkboxes are `vscode-checkbox`, and the `checked-indicator` seems to be the checkbox itself. Both of these come from the toolkit.

![image](https://github.com/microsoft/vscode-webview-ui-toolkit/assets/4691428/6ebfd933-22e4-4833-9ee0-09e4d61979b0)

We've been able to work around this by adding this to our main `App.scss`

```scss
vscode-checkbox::part(checked-indicator) {
    min-width: 16px;
}
```

**Comment by hawkticehurst** [comment]
Thanks for the heads up @benvillalobos! I'll definitely add this to backlog to look into and fix
