### ISSUE TITLE
Why is provideVSCodeDesignSystem() necessary?

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/vscode-webview-ui-toolkit#542]
### Feature request

Provide easier to use component definitions, either self-registering modules or modules that export a custom element class to register.

### Expected behavior

Elements are easier to use.

### Current behavior

Elements require an unusual boilerplate to start using:

This is the first time I've used anything based on Fast, but I couldn't get any elements to render at first, then noticed this in the docs:

```ts
import { provideVSCodeDesignSystem, vsCodeButton } from "@vscode/webview-ui-toolkit";

provideVSCodeDesignSystem().register(vsCodeButton());
```

As a user this seems like uneccessary boilerplate. Why can't I just import the library and use the components? Like:

```ts
import "@vscode/webview-ui-toolkit";
```

This is how most web components that I use behave.

**Comment by hawkticehurst** [comment]
Hey @justinfagnani!

I completely agree. This API/syntax is an artifact of how the current version of FAST works. The next major release of FAST should have an import syntax that looks closer to what you suggested.

cc @chrisdholt for further details about what the future API will look like and current timelines on the release date

**Comment by hawkticehurst** [comment]
Hi @justinfagnani, 

Back with a final update: I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
