### ISSUE TITLE
Mark React components as Pure for tree-shaking

### ISSUE THREAD

**Issue by ianobermiller** [microsoft/vscode-webview-ui-toolkit#543]
### Feature request

Mark the exported React components as pure so that bundlers can tree-shake the exports:

```tsx
export const VSCodeBadge = /* @__PURE__ */ wrap(/* @__PURE__ */ vsCodeBadge(), {
	name: 'vscode-badge',
});
```

### Expected behavior

Importing only Button and Checkbox, for example, should not pull in the entire Fast DataGrid component.

### Current behavior

Importing anything from `@vscode/webview-ui-toolkit/react` pulls in every component from `@vscode/webview-ui-toolkit`.

### Use case

I'd like to reduce my bundle size.

### Screenshots/references

As a quick example, I found that duplicating `@vscode/webview-ui-toolkit/react` with only the two components I needed (Button and Checkbox) shaved over 100KB off my minified build size.

I also manually edited `node_modules/@vscode/webview-ui-toolkit/react/index.js` two add the two pure annotations per component (note you need it for both calls) and that also worked.

**Comment by hawkticehurst** [comment]
Hi @ianobermiller,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
