### ISSUE TITLE
How to use hjkl mobile control

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode-webview-ui-toolkit#548]
How to use hjkl mobile control

**Comment by hawkticehurst** [comment]
Hi @AlaricWeb, could you please provide more information? I'm not sure what you're asking for here.

**Comment by AlaricWeb** [comment]
When I didn't ask, my English is not good, how to use hjkl keys to move up, down, left, and right on the keyboard to get the focus

**Comment by AlaricWeb** [comment]
I am used to using vim key mode. I want to make a webview table that can use hjkl as the direction key to get the focus.

**Comment by hawkticehurst** [comment]
Hi @AlaricWeb,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
