### ISSUE TITLE
Vscode peek window as a webview ui toolkit react component

### ISSUE THREAD

**Issue by pnsrinivasreddy** [microsoft/vscode-webview-ui-toolkit#549]
### Feature request

Any plans of bringing Vscode peek window https://code.visualstudio.com/docs/csharp/navigate-edit#_peek-definition as a webview ui toolkit react component

### Expected behavior
```
import { VSCodePeekWindow } from "@vscode/webview-ui-toolkit/react";

<VSCodePeekWindow>...</VSCodePeekWindow>
```

### Current behavior

Only few components are available to  use https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/react/index.ts

**Comment by hawkticehurst** [comment]
Hey @pnsrinivasreddy! 

Unfortunately, there are no plans at this time to bring a peek component to the toolkit. Thanks for the request though!
