### ISSUE TITLE
Search Input

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode-webview-ui-toolkit#552]
As a follow up to https://github.com/microsoft/vscode-webview-ui-toolkit/issues/503, can you please add a search input?

**Comment by hawkticehurst** [comment]
Hi @sketchbuch,

I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

There was an [announcement](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) last week where you can learn more details and leave any questions or comments you may have.

Beyond that, thank you so much filing this issue and apologies for never getting around to addressing it. It means a lot that you contributed to the improvement of this project. I wish you all the best in your future VS Code extension endeavors!
