### ISSUE TITLE
Controls How to modify the up and down movement buttons

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode-webview-ui-toolkit#553]
Controls How to modify the up and down movement buttons

**Comment by hawkticehurst** [comment]
Hi @AlaricWeb, could you please provide more information? I'm not sure what you're asking for here.

**Comment by hawkticehurst** [comment]
Hi @alaricweb,

Like I just mentioned in your other issue, I'm very sorry to say that the toolkit is being deprecated and all active development will be coming to a close.

Here's the [announcement link](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561) again, where you can learn more details and leave any questions or comments you may have.

Thank you again for filing this issue and apologies for never getting around to addressing it. I wish you all the best in your future VS Code extension endeavors!
