### ISSUE TITLE
Support Individual Folding of Custom Regions

### ISSUE THREAD

**Issue by DjamilaBaroudi** [microsoft/vscode-webview-ui-toolkit#554]
### Feature request

-In my VSCode extension, I'm using `languages.registerFoldingRangeProvider` to define custom folding regions in the code. However, there's currently no way to fold these regions individually. The available options, like `editor.foldAllMarkerRegions`, fold all regions at once, limiting flexibility. An enhancement to the API to allow the folding of specific custom regions will be great.

### Expected behavior
- Folding only specific regions, defined in the folding range provider.

### Use case
- Vscode extensions

**Comment by hawkticehurst** [comment]
Hey @DjamilaBaroudi! The `languages.registerFoldingRangeProvider` and `editor.foldAllMarkerRegions` APIs are actually owned by the core VS Code team, so you should make this request in the [microsoft/vscode](https://github.com/microsoft/vscode/issues) github repo.

I'm going to go ahead and close this issue, but let me know if you have any questions and I'll keep an eye out for them.
